### ISSUE TITLE
Allow support for custom certificate authorities

### ISSUE THREAD

**Issue by intmainreturnzero** [babybuddy/babybuddy-for-android#63]
Hi,

I host a babybuddy server in my home network. The server has a self-signed SSL cert and a self-created CA cert. This CA cert is added to my Android device's certificate store.

Though, still, trying to login to my babybuddy server from the Android app results in a CertPathValidationException.

**Comment by MrApplejuice** [comment]
Hey! Thanks for the bug report. I never tried this myself and (blindly) assumed that it would work out-of-the-box, but seemingly not. Hopefully something that is easy to fix... it at least sounds like it would be!

**Comment by MrApplejuice** [comment]
Good news: After some tinkering I was able to reproduce the problem! Now that that is done, I can try to address the issue!

**Comment by intmainreturnzero** [comment]
Thanks a lot for the prompt addressing of this issue! Waiting for the release with this fix!

**Comment by MrApplejuice** [comment]
Released! :+1:
