### ISSUE TITLE
More than 1 child?

### ISSUE THREAD

**Issue by maxime1992** [babybuddy/babybuddy-for-android#68]
Hello,

I read the readme and doc but this seems to only take into account 1 child.

Is it possible to handle more?

Thanks

**Comment by MrApplejuice** [comment]
Hey! You should be able to swipe the entire view from sideways... here a short clip from the emulator:

https://github.com/babybuddy/babybuddy-for-android/assets/542105/ae8bb6db-d17b-4002-be00-56be7ad6e269

Maybe important: Start swiping in the middle of the screen. Depending on your device settings, starting to swipe from the edge of the screen might be interpreted as a system-gesture.

**Comment by maxime1992** [comment]
Aaaah brilliant thanks a lot! :fire:
